(function(){
    const SM=window.SemanticMap=window.SemanticMap||{};
    const t=(ja,zh)=>SM.state.currentLang==='zh'?zh:ja;
    const esc=text=>String(text??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const glyphs=text=>Array.from(text,(char,i)=>`<span class="journey-glyph" style="--glyph-delay:${140+i*22}ms">${esc(char)}</span>`).join('');
    function person(kind='shop'){
        const shop=kind==='shop';
        return `<svg class="journey-character" viewBox="0 0 180 190" role="img" aria-label="${shop?t('お店のミナ','店主米娜'):kind==='park'?t('庭師のリリ','园丁莉莉'):t('郵便屋さんのソラ','邮差索拉')}"><ellipse cx="91" cy="180" rx="51" ry="7" fill="#d5ddc7"/><path d="M70 147v26h16v-26m16 0v26h16v-26" stroke="#596e4e" stroke-width="3" fill="#becbad"/><path d="M57 99q-17 14-19 38m84-37q25 4 26-21" class="journey-character-arm" fill="none" stroke="#708560" stroke-width="13" stroke-linecap="round"/><path d="M61 93q28-14 58 0l9 58H53Z" fill="${shop?'#849a6c':'#8d9a7c'}" stroke="#596e4e" stroke-width="2"/><path d="M70 99h40l8 49H61Z" fill="#eee8cf"/><rect x="73" y="121" width="32" height="19" rx="4" fill="#d6d9bb"/><path d="M53 73q-9-58 40-57q47 0 37 57" fill="#7d8061"/><rect x="58" y="36" width="66" height="59" rx="27" fill="#f2dec0" stroke="#7e8365" stroke-width="2"/><path d="M59 49q13-2 23-20q16 22 44 20" fill="#7d8061"/><g class="journey-character-eyes" stroke="#5d7050" stroke-width="3" stroke-linecap="round"><path d="M76 64v5m29-5v5"/></g><path d="M82 79q9 9 17 0" fill="none" stroke="#5d7050" stroke-width="2" stroke-linecap="round"/><ellipse cx="69" cy="76" rx="5" ry="2" fill="#d6b38d"/><ellipse cx="113" cy="76" rx="5" ry="2" fill="#d6b38d"/><path d="M53 34q4-28 40-27q34 0 36 27Z" fill="${shop?'#e4e4cb':'#a8b791'}" stroke="#71845d" stroke-width="2"/><path d="M48 34h87" stroke="#71845d" stroke-width="7" stroke-linecap="round"/><rect x="79" y="14" width="23" height="13" rx="3" fill="#fbf7e7"/><path d="m84 20 6 4 6-4" fill="none" stroke="#809367" stroke-width="1.5"/></svg>`;
    }
    function speech(name,line,portrait){return `<div class="journey-speech"><div class="journey-portrait" aria-hidden="true">${portrait}<i>✦</i></div><div class="journey-bubble"><span class="journey-speaker">${esc(name)}</span><p>${glyphs(line)}</p></div></div>`;}
    const primary=(icon,action,label)=>`<button class="courier-primary" data-action="${action}">${icon('arrow')}<span>${label}</span>${icon('arrow')}</button>`;
    function departure(p,api){
        const lines=[t('友だちの町へ行く郵便屋さんが、駅で待っているんだ。','去朋友那座城市的邮差，正在车站等着呢。'),t('この手紙を、一緒に届けに行こう！','一起把这封信送过去吧！'),t('今日は暑いね。冷たいものが飲みたいな。先に、キャンパスのコンビニへ寄っていこう。','今天好热啊，想喝点凉的。先去校园便利店找找吧。')];
        const beat=p.departureStep||0;
        return {world:`<div class="journey-departure-stage" data-departure-beat="${beat}"><div class="journey-main-title"><small>${t('新しい旅のはじまり','新的旅程')}</small><h1>${t('手紙を、届けに。','一起去送信。')}</h1></div><div class="journey-envelope">${api.icon('mail')}<span>${t('友だちへ','给朋友')}</span><b>P</b></div><div class="journey-departure-poco tutorial-poco-speaking"><div class="opening-invite" role="status"><span class="opening-speaker">${t('ポコ','波可')}</span><p>${glyphs(lines[beat])}</p></div>${api.robot()}</div><div class="journey-destination">${api.icon('station')}<div><small>${t('お届け先','目的地')}</small><strong>${t('JR茨木駅前の郵便屋さん','JR 茨木站前的邮差')}</strong></div></div><i class="journey-scene-star">✦</i><i class="journey-scene-star second">✦</i></div>`,body:'',footer:primary(api.icon,beat<2?'departure-next':'journey-map',beat<2?t('つづける','继续'):t('地図をひらく','展开地图'))};
    }
    const names=i=>i===1?t('ミナ','米娜'):i===2?t('リリ','莉莉'):t('ソラ','索拉');
    function travel(p,api){
        const i=p.index;
        const line=i===1?t('あのお店で、冷たい飲みものを探そう。駅までの道で飲めるといいな。','去那家店找一份冷饮吧，可以带在去车站的路上喝。'):i===2?t('公園を通っていこう。友だちにも、この街の緑を見せたいな。','经过公园时，也给朋友带一份这座城市的绿色吧。'):t('駅前でソラが待っているよ。もう少しで、手紙を渡せるね。','索拉就在车站前等着。马上就能把信交给他了。');
        const arrival=i===1?t('コンビニに着いた','我到便利店了'):i===2?t('公園に着いた','我到公园了'):t('駅に着いた','我到车站了');
        const arrivalHint=i===1?t('A棟1Fへ。お店に着いたら、下のボタンをタップ。','前往 A 栋 1F，到店后点击下方按钮。'):i===2?t('公園に着いたら、下のボタンをタップ。','到公园后，点击下方按钮。'):t('駅の東口に着いたら、下のボタンをタップ。','到车站东口后，点击下方按钮。');
        return {body:`<section class="journey-travel"><div class="journey-stop-card">${api.icon(i===1?'drink':i===2?'leaf':'station')}<div><small class="journey-stop-label">${t('つぎの立ち寄り先','下一站')}</small><strong>${esc(api.step.place)}</strong><span data-journey-distance>${t('地図の「！」が目印','地图上的「！」就是目的地')}</span></div><b>!</b></div>${speech(t('ポコ','波可'),line,api.robot())}</section>`,footer:`<p class="journey-footer-note">${arrivalHint}</p>`+primary(api.icon,'arrive',arrival)+`<div class="courier-action-links"><button class="courier-text" data-action="journal">${t('郵便バッグ','查看邮包')}</button></div>`};
    }
    function encounter(p,api){
        const i=p.index,shop=i===1,first=shop&&!p.encounterStep;
        const line=first?t('今日は暑いね。ポコ、駅まで歩くなら、冷たい飲みものを持っていくといいよ。','今天好热啊。波可，要走去车站的话，带一份冷饮吧。'):shop?t('水でも、お茶でも、ジュースでも。ポコに持たせたい飲みものを、写真に撮ってね。','水、茶、果汁都可以。拍一份想让波可带上的饮料吧。'):i===2?t('友だちに見せたい緑を、一枚撮っていこう。木でも、葉っぱでもいいよ。','拍一份想给朋友看的绿色吧。树、叶子都可以。'):t('手紙を届けに来たんだね。まずは「茨木」の駅名を写真に撮って、ここが待ち合わせ場所だと確かめよう。','是来送信的吧。先拍下「茨木」站名，确认这里就是会合地点。');
        return {body:`<section class="journey-encounter" data-encounter="${first?'greeting':'quest'}"><div class="journey-shop-stage ${shop?'':'journey-outdoor'}"><div class="journey-shop-awning"><i></i><i></i><i></i><i></i><i></i><i></i></div><span class="journey-shop-sign">${shop?'MINA’S SHOP':i===2?'IWAKURA PARK':'IBARAKI POST'}</span><div class="journey-shop-window">${api.icon(shop?'drink':i===2?'tree':'mail')}</div>${person(api.step.scene)}<div class="journey-counter"><span>${esc(api.step.place)}</span></div><span class="journey-npc-mark">!</span></div>${speech(names(i),line,person(api.step.scene))}${first?'':`<article class="journey-quest-ticket"><div class="journey-ticket-top"><span>${t('小さな委託','小小的委托')}</span><b>${i===1?'01':i===2?'02':'03'}</b></div><h2>${shop?t('冷たい飲みものを届けよう','给波可送一份冷饮'):i===2?t('緑の思い出を添えよう','附上一份绿色的回忆'):t('待ち合わせ場所を確かめよう','确认会合地点')}</h2><p>${shop?t('水・お茶・ジュースなど、冷たい飲みものをひとつ撮ろう。','拍一份水、茶、果汁等冷饮。'):i===2?t('木や葉っぱを、ひとつ撮ろう。','拍下一棵树或一片叶子。'):t('「茨木 / Ibaraki」の駅名を撮ろう。',api.step.goal)}</p><span class="journey-ticket-reward">${api.icon('check')}${t('この場所の郵便スタンプ','获得这一站的邮戳')}</span></article>`}</section>`,footer:first?primary(api.icon,'shop-talk',t('冷たい飲みものを探す','找一份冷饮')):`<p class="journey-footer-note">${shop?t('お店で撮影できるものを選んでね。','选一份店内允许拍摄的饮料。'):i===2?t('摘み取らず、目の前の緑を撮ろう。',api.step.hint):t('駅の外で撮影できます。改札に入る必要はありません。',api.step.hint)}</p>`+`<button class="courier-primary" data-action="photo">${api.icon('camera')}<span>${shop?t('飲みものを撮ろう','拍一份饮料'):t('写真を撮ろう','拍张照片')}</span>${api.icon('arrow')}</button>`+(api.localTest?`<button type="button" class="courier-text journey-test-skip" data-action="skip-photo">${t('テスト：撮影をスキップ','测试：跳过拍摄')}</button>`:'')+`<div class="courier-action-links">${api.localTest&&p.mode==='preview'?`<button class="courier-text" data-action="sample">${t('テスト：写真を補う','测试：使用示例')}</button>`:''}<button class="courier-text" data-action="journal">${t('郵便バッグを見る','看看邮包')}</button></div>`};
    }
    function receipt(p,api){
        const card=p.cards.find(c=>c.step===p.index),shop=p.index===1,packed=!shop||p.packed;
        const line=shop?t('ありがとう！これで途中にのどが渇いても大丈夫だね。','谢谢！这样路上口渴了也有饮料啦。'):p.index===2?t('この緑も手紙と一緒に届けよう。友だちに見てもらうのが楽しみだね。','把这份绿色和信一起送去吧。真想让朋友看看。'):t('ここが待ち合わせ場所だね。ソラに、手紙を渡そう。','就是这里了。把信交给索拉吧。');
        return {body:`<section class="journey-receipt ${packed?'supply-packed':''}"><p class="journey-eyebrow" role="status">${packed?t('委託完了','委托完成'):t('写真から、届いた！','从照片里送来了！')}</p><h2>${packed?shop?t('飲みもの、準備できた！','饮料，准备好了！'):t('心意、そろいました。','心意，收好了。'):t('これを、ポコのバッグへ。','把它装进波可的邮包吧。')}</h2><figure class="journey-item-card">${card.photo?`<img src="${esc(card.photo)}" alt="${esc(card.word)}">`:`<div class="journey-item-example">${api.icon(shop?'drink':p.index===2?'leaf':'station')}<small>${t('テスト用の写真','测试照片')}</small></div>`}<figcaption><ruby>${esc(card.word)}<rt>${esc(card.kana)}</rt></ruby></figcaption></figure><div class="journey-bag-row"><span class="journey-bag-line" aria-hidden="true">✦ · · ·</span><div class="journey-bag">${api.icon('mail')}<span>POCO</span>${packed?'<b>✓</b>':''}</div></div>${packed?`<div class="journey-clear-stamp">${api.icon('check')}<strong>${esc(t(['','OIC · 飲みもの','公園 · 緑の思い出','JR 茨木 · 待ち合わせ'][p.index],api.step.stamp))}</strong><span>${t('準備完了','准备完成')}</span></div>${speech(t('ポコ','波可'),line,api.robot())}`:''}</section>`,footer:primary(api.icon,packed?'next':'pack',packed?p.index===3?t('ソラに手紙を渡す','把信交给索拉'):t('配達を続ける','继续送信'):t('郵便バッグに入れる','装进邮包'))};
    }
    function handoff(api){return `<div class="journey-handoff">${speech(t('ソラ','索拉'),t('預かった手紙は、ぼくが友だちの町へ届けるよ。','把信交给我吧，我会把它送到朋友的城市。'),person('station'))}<button class="journey-envelope journey-envelope-button" data-action="deliver-letter" aria-label="${t('手紙をソラに渡す','把信交给索拉')}">${api.icon('mail')}<span>${t('友だちへ','给朋友')}</span><b>P</b></button><p>${t('封筒をタップして、手紙を渡そう。','点一下信封，把信交出去。')}</p></div>`;}
    function ending(p,api){return {body:`<section class="journey-ending"><div class="journey-clear-stamp">${api.icon('check')}<strong>${t('配達完了','送信完成')}</strong><span>JR IBARAKI</span></div><h2>${t('きみの手紙が、<br>遠くへ旅立った。','你的信，<br>出发去远方了。')}</h2>${speech(t('ポコ','波可'),t('一緒に届けてくれて、ありがとう。次は、友だちからの返事を待とうね。','谢谢你陪我送信。接下来，一起期待朋友的回信吧。'),api.robot())}<div class="journey-collected">${p.cards.map(c=>`<span>${api.icon(c.object==='drink'?'drink':c.object==='letter'?'mail':c.object==='station'?'station':'leaf')}${esc(c.word)}</span>`).join('')}</div></section>`,footer:primary(api.icon,'journal',t('旅の手帳をひらく','翻开这次旅途的手帐'))+`<button class="courier-text courier-restart" data-action="restart">${t('もう一度、一緒に出かける','再陪波可走一次')}</button>`};}
    SM.deliveryScenes={departure,travel,encounter,receipt,handoff,ending,person};
})();
