import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const origin=process.env.COURIER_TEST_ORIGIN || 'http://127.0.0.1:8000/';
const browser=await chromium.launch();
const errors=[];
const fixture='assets/lumi-avatar.png';
await fs.mkdir('screenshots',{recursive:true});
async function fresh(viewport={width:1440,height:1000}) {
    const context=await browser.newContext({viewport});
    const page=await context.newPage();page.setDefaultTimeout(12000);
    page.on('pageerror',error=>errors.push(error.message));
    await page.addInitScript(()=>{
        window.gpsRequests=0;
        navigator.geolocation.watchPosition=()=>{window.gpsRequests++;return 1;};
        navigator.geolocation.clearWatch=()=>{};
    });
    await page.goto(origin,{waitUntil:'networkidle'});
    return page;
}
function mockPhotos(page) {
    const control={status:200,mismatch:false,wordOverride:null,kanaOverride:null,requests:[]};
    const names={pen:['ペン','ぺん'],food:['りんご','りんご'],cute:['花','はな'],drink:['牛乳','ぎゅうにゅう']};
    page.route('**/api/gemini',async route=>{
        const payload=route.request().postDataJSON();
        const text=payload.contents[0].parts[0].text;
        const key=text.match(/Current task key: (\w+)/)?.[1];
        assert(key&&names[key]);assert(payload.contents[0].parts[1].inline_data.data);
        assert.deepEqual(payload.generationConfig.response_schema.required,['match','object','word','kana']);
        assert(payload.generationConfig.response_schema.properties.object.enum.includes(key));
        control.requests.push(key);
        const [word,kana]=names[key];
        await route.fulfill({status:control.status,contentType:'application/json',body:JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify({match:!control.mismatch,object:control.mismatch?'other':key,word:control.wordOverride||word,kana:control.kanaOverride||kana})}]}}]})});
    });
    return control;
}
async function meetPoco(page) {
    assert.match(await page.locator('.opening-invite').innerText(),/ぼくはポコ/);
    await page.locator('[data-letter-action="open"]').click();
    assert.equal(await page.locator('.incoming-letter').count(),0);
    assert.match(await page.locator('.opening-invite').innerText(),/友だちに手紙を書きたい/);
    await page.reload({waitUntil:'networkidle'});
    assert.match(await page.locator('.opening-invite').innerText(),/ぼくはポコ/);
    await page.locator('[data-letter-action="open"]').click();
    assert.match(await page.locator('.opening-invite').innerText(),/友だちに手紙を書きたい/);
    await page.locator('[data-letter-action="open"]').click();
    assert.equal(await page.locator('.incoming-letter').count(),0);
    assert.match(await page.locator('.opening-invite').innerText(),/ペンが見つからない/);
    assert.equal(await page.locator('[data-letter-action="photo"]').count(),0);
    await page.locator('[data-letter-action="open"]').click();
    assert.match(await page.locator('.opening-invite').innerText(),/写真.*本物/);
    assert.equal(await page.locator('[data-letter-action="photo"]').count(),0);
    await page.locator('[data-letter-action="open"]').click();
    await page.locator('[data-letter-action="photo"]').waitFor();
    assert.match(await page.locator('.opening-invite').innerText(),/ペン.*写真/);
    assert.equal(await page.locator('#courier-app.courier-opening').count(),1);
    assert.equal(await page.locator('.tutorial-task-title').count(),0);
    assert.equal(await page.locator('.incoming-letter,[data-letter-action="reply"]').count(),0);
}
async function openWriting(page) {
    await meetPoco(page);
    await page.locator('#courier-file').setInputFiles(fixture);
    await page.locator('[data-letter-action="start-writing"]').click();
    await page.locator('[data-letter-slot="food"]').first().waitFor();
}
async function capture(page,key) {
    await page.locator(`[data-letter-slot="${key}"]`).first().click();
    await page.locator('#courier-file').setInputFiles(fixture);
    await page.locator(`[data-letter-slot="${key}"].filled`).waitFor();
    await page.waitForFunction(()=>!document.querySelector('#courier-app').classList.contains('letter-receiving'));
}
async function sample(page,key){await page.locator('[data-action="sample"]').click();await page.locator(`[data-sample="${key}"]`).click();}
async function checkCompletion(page) {
    await page.locator('.letter-completion').waitFor();
    assert.equal(await page.locator('.completion-card').count(),3);
    assert.equal(await page.locator('.completion-photo img').count(),3);
    assert.deepEqual(await page.locator('.completion-photo img').evaluateAll(images=>images.map(img=>img.getAttribute('src'))),await page.locator('.materialized-item img').evaluateAll(images=>images.map(img=>img.getAttribute('src'))));
    assert.equal(await page.locator('.completion-card rt').count(),3);
    assert.match(await page.locator('.completion-kicker').innerText(),/委託完了|委托完成/);
    assert.match(await page.locator('.completion-letter .reply-letter').innerText(),/友だちへ[\s\S]*そっちは、最近どう？[\s\S]*ポコ/);
    assert.equal(await page.locator('.letter-completion .letter-slot').count(),0);
    assert.equal(await page.locator('.tutorial-poco [data-expression="happy"]').count(),1);
    assert.equal(await page.locator('.completion-poco-avatar [data-expression="happy"]').count(),1);
    assert.equal(await page.evaluate(()=>window.gpsRequests),0);
    const top=await page.locator('[data-letter-action="field"]').boundingBox();
    await page.locator('#courier-story-body').evaluate(el=>el.scrollTop=el.scrollHeight);
    const bottom=await page.locator('[data-letter-action="field"]').boundingBox();
    assert.equal(top.y,bottom.y);
    assert(bottom.y>=0&&bottom.y+bottom.height<=page.viewportSize().height);
    const header=await page.locator('.courier-story-header').boundingBox();
    assert(header.y>=0&&header.y+header.height<=page.viewportSize().height);
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.locator('#courier-story-body').evaluate(el=>el.scrollTop=0);
}
try {
    const p=await fresh();const mock=mockPhotos(p);
    assert.equal(await p.locator('[data-action="sample"], [data-action="alternate"]').count(),0);
    assert.equal(await p.evaluate(()=>window.gpsRequests),0);
    await p.screenshot({path:'screenshots/letter-opening-desktop.png'});
    await meetPoco(p);
    assert.match(await p.locator('.opening-invite').innerText(),/ペン.*写真/);
    mock.mismatch=true;await p.locator('#courier-file').setInputFiles(fixture);
    await p.getByRole('heading',{name:/別の写真で試してみよう|再找找这件东西/}).waitFor();
    assert.equal(await p.locator('.reply-letter').count(),0);
    await p.locator('#courier-dialog [data-action="close"]').click();
    mock.mismatch=false;mock.status=503;await p.locator('#courier-file').setInputFiles(fixture);
    await p.getByRole('heading',{name:/写真が届きませんでした|照片暂时没能送达/}).waitFor();
    assert.equal(await p.locator('[data-action="sample"]').count(),0);
    await p.locator('#courier-dialog [data-action="close"]').click();
    mock.status=200;await p.locator('#courier-file').setInputFiles(fixture);
    await p.locator('[data-letter-action="start-writing"]').click();
    await p.locator('[data-letter-slot="food"]').waitFor();
    assert.equal(await p.locator('.letter-slot').count(),1);
    assert.equal(await p.locator('[data-letter-slot="cute"],[data-letter-slot="drink"]').count(),0);
    assert.equal(await p.locator('[data-letter-action="send"]').count(),0);
    await p.screenshot({path:'screenshots/letter-writing-desktop.png'});
    await capture(p,'food');await capture(p,'cute');
    await p.reload({waitUntil:'networkidle'});
    assert.match(await p.locator('.opening-invite').innerText(),/ぼくはポコ/);
    assert.equal(await p.locator('.letter-slot').count(),0);
    assert.equal(await p.evaluate(()=>window.gpsRequests),0);
    await openWriting(p);await capture(p,'food');await capture(p,'cute');
    assert.equal(await p.locator('.letter-slot.filled').count(),2);
    assert.equal(await p.evaluate(()=>localStorage.getItem('kotoba-hunter-letter-tutorial-v1')),null);
    await capture(p,'drink');
    assert.equal(await p.locator('.materialized-item').count(),3);
    assert.match(await p.locator('.reply-letter').innerText(),/今朝は、\s*りんご/);
    mock.wordOverride='パン';mock.kanaOverride='ぱん';await p.locator('[data-letter-slot="food"]').first().click();
    await p.locator('[data-letter-action="retake"]').click();
    await p.locator('#courier-file').setInputFiles(fixture);
    await p.waitForFunction(()=>document.querySelector('[data-letter-slot="food"]').textContent.includes('パン'));
    await p.waitForFunction(()=>!document.querySelector('#courier-app').classList.contains('letter-receiving'));
    assert.equal(await p.locator('.letter-slot.filled').count(),3);mock.wordOverride=null;mock.kanaOverride=null;
    await p.screenshot({path:'screenshots/letter-completed-desktop.png'});
    await p.locator('[data-letter-action="send"]').click();
    await checkCompletion(p);
    assert.equal(await p.locator('.completion-card ruby').nth(0).evaluate(el=>el.firstChild.textContent),'パン');
    assert.equal(await p.locator('.completion-card rt').nth(0).innerText(),'ぱん');
    assert.equal(await p.locator('.completion-card ruby').nth(1).evaluate(el=>el.firstChild.textContent),'花');
    assert.equal(await p.locator('.completion-card rt').nth(1).innerText(),'はな');
    assert.equal(await p.locator('.completion-card ruby').nth(2).evaluate(el=>el.firstChild.textContent),'牛乳');
    assert.equal(await p.locator('.completion-card rt').nth(2).innerText(),'ぎゅうにゅう');
    assert.equal(await p.locator('[data-letter-action="field"]').count(),1);
    assert.equal(await p.evaluate(()=>window.gpsRequests),0);
    await p.locator('[data-letter-action="stay"]').click();
    assert.match(await p.locator('#courier-status').innerText(),/ありがとう/);
    await p.locator('[data-letter-action="field"]').click();
    assert.equal(await p.locator('#courier-app.courier-tutorial').count(),0);
    assert.equal(await p.evaluate(()=>window.gpsRequests),0);
    await p.locator('[data-action="departure-next"]').click();
    await p.locator('[data-action="departure-next"]').click();
    await p.locator('[data-action="journey-map"]').click();
    assert.equal(await p.evaluate(()=>window.gpsRequests),1);
    assert.match(await p.locator('.journey-stop-card').innerText(),/Seven-Eleven/);
    await p.locator('[data-action="arrive"]').click();
    await p.locator('[data-action="shop-talk"]').click();
    await p.locator('[data-action="mode"]').click();await p.locator('[data-action="preview-mode"]').click();
    await sample(p,'drink');await p.locator('[data-action="pack"]').click();await p.locator('[data-action="next"]').click();await p.locator('[data-action="arrive"]').click();
    await p.screenshot({path:'screenshots/oic-courier-park.png'});
    await sample(p,'leaf');await p.locator('[data-action="next"]').click();await p.locator('[data-action="arrive"]').click();
    await sample(p,'station');await p.locator('[data-action="next"]').click();
    await p.locator('[data-action="deliver-letter"]').first().click();
    assert.equal(await p.locator('.journey-collected>span').count(),4);
    await p.locator('[data-action="restart"]').click();await p.locator('[data-action="confirm-restart"]').click();
    assert.equal(await p.locator('[data-letter-action="open"]').count(),1);
    await p.evaluate(()=>{
        const photo=document.createElement('canvas').toDataURL('image/jpeg');const card={word:'ペン',kana:'ぺん',photo};
        localStorage.setItem('kotoba-hunter-letter-tutorial-v1',JSON.stringify({phase:'sent',introduced:true,captures:{pen:card,food:card,cute:card,drink:card},finished:true}));
        localStorage.setItem('oic-courier-story-v2',JSON.stringify({index:1,cards:[{step:0,object:'letter',word:'手紙'}],mode:'field'}));
        localStorage.setItem('courier-unrelated-test','keep');
    });
    await p.reload({waitUntil:'networkidle'});
    assert.match(await p.locator('.opening-invite').innerText(),/ぼくはポコ/);
    assert.equal(await p.evaluate(()=>window.gpsRequests),0);
    assert.equal(await p.evaluate(()=>localStorage.getItem('kotoba-hunter-letter-tutorial-v1')),null);
    assert.equal(await p.evaluate(()=>localStorage.getItem('oic-courier-story-v2')),null);
    assert.equal(await p.evaluate(()=>localStorage.getItem('courier-unrelated-test')),'keep');
    const mobile=await fresh({width:390,height:844});mockPhotos(mobile);
    await mobile.screenshot({path:'screenshots/letter-opening-mobile.png'});
    await openWriting(mobile);await mobile.screenshot({path:'screenshots/letter-writing-mobile.png'});
    await mobile.setViewportSize({width:320,height:568});
    await mobile.locator('#courier-story-body').evaluate(el=>el.scrollTop=el.scrollHeight);
    let rect=await mobile.locator('[data-letter-action="photo"]').boundingBox();
    assert(rect.y>=0&&rect.y+rect.height<=568);
    assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await mobile.locator('[data-action="journal"]').click();
    await mobile.locator('#courier-dialog-body').evaluate(el=>el.scrollTop=el.scrollHeight);
    rect=await mobile.locator('#courier-dialog>header').boundingBox();assert(rect.y>=0);
    rect=await mobile.locator('#courier-dialog-footer').boundingBox();assert(rect.y+rect.height<=568);
    await mobile.locator('#courier-dialog [data-action="close"]').first().click();
    for(const key of ['food','cute','drink'])await capture(mobile,key);
    await mobile.locator('#courier-story-body').evaluate(el=>el.scrollTop=el.scrollHeight);
    rect=await mobile.locator('[data-letter-action="send"]').boundingBox();assert(rect.y+rect.height<=568);
    await mobile.locator('[data-letter-action="send"]').click();
    await checkCompletion(mobile);
    await mobile.waitForTimeout(1500);
    await mobile.screenshot({path:'screenshots/letter-sent-mobile.png'});
    await mobile.emulateMedia({reducedMotion:'reduce'});
    await mobile.reload({waitUntil:'networkidle'});
    await mobile.evaluate(()=>{window.SemanticMap.letterTutorial.testStart('sent');document.querySelector('[data-action="language"]').click();});
    await checkCompletion(mobile);
    assert.equal(await mobile.locator('.completion-postmark').evaluate(el=>getComputedStyle(el).animationName),'none');
    await mobile.locator('[data-letter-action="field"]').click();
    assert.equal(await mobile.locator('#courier-app.courier-sent').count(),0);
    assert.equal(await mobile.evaluate(()=>window.gpsRequests),0);
    await mobile.locator('[data-action="departure-next"]').click();
    await mobile.locator('[data-action="departure-next"]').click();
    await mobile.locator('[data-action="journey-map"]').click();
    assert.equal(await mobile.evaluate(()=>window.gpsRequests),1);
    assert.deepEqual(errors,[]);
    console.log('PASS: POCO conversation and pen; one photo question at a time; delivery celebration then next paragraph; mismatch/service error; retake; reload resets introduction, photos and legacy field progress; no progress persisted; no GPS until explicit field start; route and ending; restart; 320px fixed controls; no runtime errors. Photo recognition mocked.');
} finally {await browser.close();}
